service: serverless-tracker
plugins:
  - serverless-python-requirements
  - serverless-wsgi
custom:
  wsgi:
    app: app.app
    packRequirements: false
    pythonBin: venv/bin/python
  pythonRequirements:
    dockerizePip: true
package:
  exclude:
    - node_modules/**
    - venv/**
provider:
  name: aws
  runtime: python3.7
  profile: angent_richard
  stage: dev
  region: eu-west-2
functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
